### ISSUE TITLE
Jenkins中上游job触发下游job,下游job构建完成后，推送微信消息出现异常

### ISSUE THREAD

**Issue by wangshengshun** [AIKiller/jenkins-weixin-qiye-alert#6]
项目构建结束
ERROR: Build step failed with exception
java.lang.NullPointerException
	at com.killer.weixin.WeixinServiceImpl.init(WeixinServiceImpl.java:152)
	at com.killer.weixin.WeixinServiceImpl.success(WeixinServiceImpl.java:123)
	at com.killer.weixin.WeixinNotifier.perform(WeixinNotifier.java:118)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:74)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1742)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Build step 'Weixin message Pusher' marked build as failure

**Comment by AIKiller** [comment]
之前写这个插件主要是为了解决我们团队的消息推送的问题，我们使用的是pipeline的方式，所以传统的上游job引用下游job的方式并没刻意的去兼容。 这个应该是某些信息在上下游之间发生丢失造成。最近我会尝试修复一下这个问题。

**Comment by wangshengshun** [comment]
你那边修复完成这个问题后，我这边再试试看
